### ISSUE TITLE
Ресурс: цели

### ISSUE THREAD

**Issue by vovs03** [ro31337/rubyschool#2]
Роман, приветствую! 
В чате телеграм недавно, я вообще можно сказать новичок в Ruby и RoR. Но в последнее время меня привлекают ЯП: **JavaScript**, **Python**, **Ruby**(& **RoR**). 
Хочу поучаствовать в развитии проекта, и соответственно есть вопросы(точки соприкосновения) как и что, и почему так... Ok, let's go.

# Цель ресурса rubyschool.us
Как я понимаю, то вот некоторые из образовательных целей ресурса:
- [x] познакомить гика с языком программирования **Ruby**;
- [x] познакомить с фреймворком **RoR (Ruby on Rails)** для написания Web apps ( вэб-сайтов);
- [ ] создание Forum для поддержки учеников;
- [x] [чат-телеграмм](https://t.me/rubyschool) (для учеников и не только)

## 1. Аудитория
Преимущественно гики, или все, кому интересен электронный мир и программирование (кодинг)?
### 1.1 Возраст
- 13-17; 
- 18-24
- 25-34
- 35+

### 1.2 Территория, или выбор языка

- [ ] **?**  `CountryCommunity = Students['Russians','Americans','AllWorld']`
А то сайт в домене .us но на русском языке, будет ли он на англ?

### 1.3 База подписчиков
- [ ] Сбор Контактов

## 2. Информирование, раскрутка и Продвижение.
- Есть ли в планах размещение видео-уроков на [YouTube](https://www.youtube.com)?
- Как люди будут находить ресурс?
- Ведение рассылки с базой подписчиков.

## 3. Площадки
- [x] [Сайт RubySchool.us](http://RubySchool.us)
- [ ] Форум
- [x] [чат-телеграмм](https://t.me/rubyschool)
- [ ] [Код, размещённый на GitHub](https://github.com/ro31337/rubyschool)

### 3.1 Сайт
- рукописный?
- на движке?(WordPress)
- фреймворк?(RoR)
- Многостраничный / LandingPage
- SEO-optimization
- [ ] Определить Frontend/BackEnd

### 4.1 Формат уроков
- Видео
- Пост
- Сопровождение урока (код, или фрагмент кода)

### 4.2 Структурирование учебного материала
- [ ] Уроки сгруппированы по модулям;
- [ ] Модуль разбит на блоки;
- [ ] В каждом блоке уроки, имеющие **Тему**
- [ ] В каждой теме разбивка на подпункты.

### 4.3 Маркировка урока по уровню сложности:
1. базовый;
2. средний;
2. гуру;

## 5. Монетизация или Donate
- Оплата курса через PayPal (другие платёжные системы)
- Поддержка сайта, принимаем пожертвование на развитие проекта, оплата хостинга, домена...
Если оплата, то почему сайт до сих пор **_http_** а не **https**?
- [ ] Определиться с ценовой политикой курсов.

Вот, вопросы, на которые хотелось бы услышать ответы. Не имея общего видения сложно прийти к поставленной цели ;)

**Comment by ro31337** [comment]
Спасибо за вопросы, дам развернутый ответ и закину на главную.

**Comment by vovs03** [comment]
6дней прошло... В курсе событий. Но ясности по этому выпуску пока что нет. Может стоит раздробить его на 5вопросов?
