### ISSUE TITLE
Unblocking Telegram

### ISSUE THREAD

**Issue by vovs03** [ro31337/rubyschool#20]
Если есть возможность, опишите **шаги разблокировки Телеграмм** чтобы зайти в чат [Rubyschool](https://telegram.me/rubyschool). Спасибо

**Comment by vovs03** [comment]
порыскал, был тут:

- https://tlgrm.ru/faq/obhod-blokirovki-telegram.html потом в комментах нашёл след. линк:
- https://github.com/schors/tgdante2

просто сейчас нет времени на установку докера и опробирование (у меня только десктоп-версия телеграма)

**Comment by ro31337** [comment]
Привет. Так давай pull request к главной странице. Прямо в браузере можешь менять https://github.com/ro31337/rubyschool/blob/master/index.html . Только напиши все правильно и проверь. И сразу появится на rubyschool.us

**Comment by vovs03** [comment]
К сожалению, у меня сейчас реально нет времени, сборы перед отъездом, неделю меня не будет, вернусь только 7-8 мая, тогда конечно если PR не будет ещё - то займусь

**Comment by ro31337** [comment]
Ладно, тогда пока закрою
